name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
      with:
        egress-policy: audit

    - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@edee9537367a8fbc625d27f9e10aa8bad47b8723 # v1.13.0
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: Ghost-ate-your-brains
          numOfAssignee: 1